#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="/var/lib/mario/libexec"

if ! [ -d $libexec_path ]; then
  mario_executable_path=$(realpath $0)
  libexec_path=$(dirname $mario_executable_path)
fi

export _MARIO_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec mario-help
  ;;
* )
  command_path="$(command -v "mario-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "mario: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
